openai:
  api_key: sk-BKR5huAmRgTd1qjwP6AWocZXvmgTjJ2UI46uiHi104YT4Jnh
  base_url: https://api.openai-proxy.org/v1
  max_per_tokens: 4096
  model: gpt-4o-mini
project:
  config_file_ext:
  - .yaml
  - .xml
  - .json
  - .conf
  - .ini
  - .toml
  - .config
  - .settings
  exclude_dir:
  - node_modules
  - dist
  - build
  - out
  - venv
  - .venv
  - env
  - target
  - vendor
  - bower_components
  - .git
  - .svn
  - .hg
  - .idea
  - .vscode
  - .metadata
  - nbproject
  - test
  - tests
  - spec
  - specs
  - tmp
  - temp
  - cache
  - logs
  - docker
  - containers
  - k8s
  - kube
  - .circleci
  - .github
  - .travis
  - docs
  - doc
  - .secrets
  - .env
  exclude_max_file_size: 1
  source_file_ext:
  - .py
  - .go
  - .js
  - .java
  - .cpp
  - .php
  - .aspx
  - .asp
  - .c
  - .cs
